In [1]:
import numpy as np

In [2]:
START_OFFSET = 81
P_NUMBER = 1
S_NUMBER = 5
B_NUMBER = 2
L_NUMBER = 4
Z_NUMBER = 4
T_NUMBER = 5

P_OFFSET = START_OFFSET
S_OFFSET = P_OFFSET + P_NUMBER
B_OFFSET = S_OFFSET + S_NUMBER
L_OFFSET = B_OFFSET + B_NUMBER
Z_OFFSET = L_OFFSET + L_NUMBER
T_OFFSET = Z_OFFSET + Z_NUMBER

In [3]:
def P_NEUTRAL(i, j):
    return [(i, j)]

In [4]:
def S_NEUTRAL(i, j):
    return [(i, j), (i, j+1), (i+1, j), (i+1, j+1)]

In [5]:
def B_UP_DOWN(i, j):
    return [(i, j), (i+1, j), (i+2, j), (i+3, j)]

In [6]:
def B_LEFT_RIGHT(i, j):
    return [(i, j), (i, j+1), (i, j+2), (i, j+3)]

In [7]:
def L_UP_LEFT(i, j):
    return [(i, j), (i+1, j), (i+1, j+1), (i+1, j+2)]

In [8]:
def L_UP_RIGHT(i, j):
    return [(i, j+2), (i+1, j), (i+1, j+1), (i+1, j+2)]

In [9]:
def L_DOWN_LEFT(i, j):
    return [(i+1, j), (i, j), (i, j+1), (i, j+2)]

In [10]:
def L_DOWN_RIGHT(i, j):
    return [(i, j), (i, j+1), (i, j+2), (i+1, j+2)]

In [11]:
def L_VERT_UP_LEFT(i, j):
    return [(i, j), (i, j+1), (i+1, j+1), (i+2, j+1)]

In [12]:
def L_VERT_UP_RIGHT(i, j):
    return [(i, j), (i+1, j), (i+2, j), (i, j+1)]

In [13]:
def L_VERT_DOWN_LEFT(i, j):
    return [(i+2, j), (i, j+1), (i+1, j+1), (i+2, j+1)]

In [14]:
def L_VERT_DOWN_RIGHT(i, j):
    return [(i, j), (i+1, j), (i+2, j), (i+2, j+1)]

In [15]:
def Z_LEFT(i, j):
    return [(i, j), (i, j+1), (i+1, j+1), (i+1, j+2)]

In [16]:
def Z_RIGHT(i, j):
    return [(i+1, j), (i+1, j+1), (i, j+1), (i, j+2)]

In [17]:
def Z_UP(i, j):
    return [(i, j), (i+1, j), (i+1, j+1), (i+2, j+1)]

In [18]:
def Z_DOWN(i, j):
    return [(i, j+1), (i+1, j), (i+1, j+1), (i+2, j)]

In [19]:
def T_UP(i, j):
    return [(i, j+1), (i+1, j), (i+1, j+1), (i+1, j+2)]

In [20]:
def T_DOWN(i, j):
    return [(i, j), (i, j+1), (i, j+2), (i+1, j+1)]

In [21]:
def T_LEFT(i, j):
    return [(i, j+1), (i+1, j), (i+1, j+1), (i+2, j+1)]

In [22]:
def T_RIGHT(i, j):
    return [(i, j), (i+1, j), (i+2, j), (i+1, j+1)]

In [23]:
mat = [[0 for i in range(3)] for j in range(3)]

In [24]:
print(mat)

[[0, 0, 0], [0, 0, 0], [0, 0, 0]]


In [25]:
mat = np.asarray(mat)

In [26]:
mat

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [27]:
def filled_mat(func):
    mat = np.zeros((4, 4))
    for i in range(4):
        for j in range(4):
            if (i, j) in func(0, 0):
                mat[i][j] = 1
    return mat

In [28]:
filled_mat(P_NEUTRAL)

array([[1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
print(filled_mat(P_NEUTRAL))

[[1. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [30]:
functions = [P_NEUTRAL, S_NEUTRAL, B_UP_DOWN, B_LEFT_RIGHT, L_UP_LEFT, L_UP_RIGHT, L_DOWN_LEFT, L_DOWN_RIGHT, L_VERT_UP_LEFT, L_VERT_UP_RIGHT, L_VERT_DOWN_LEFT, L_VERT_DOWN_RIGHT, Z_LEFT, Z_RIGHT, Z_UP, Z_DOWN, T_UP, T_DOWN, T_LEFT, T_RIGHT]

In [31]:
print(functions[0].__name__, filled_mat(functions[0]), sep="\n")

P_NEUTRAL
[[1. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [32]:
def print_tetromino(func):
    print(func.__name__, filled_mat(func), sep="\n")

In [33]:
print_tetromino(functions[0])

P_NEUTRAL
[[1. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [34]:
for func in functions:
    print_tetromino(func)

P_NEUTRAL
[[1. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
S_NEUTRAL
[[1. 1. 0. 0.]
 [1. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
B_UP_DOWN
[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]]
B_LEFT_RIGHT
[[1. 1. 1. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
L_UP_LEFT
[[1. 0. 0. 0.]
 [1. 1. 1. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
L_UP_RIGHT
[[0. 0. 1. 0.]
 [1. 1. 1. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
L_DOWN_LEFT
[[1. 1. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
L_DOWN_RIGHT
[[1. 1. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
L_VERT_UP_LEFT
[[1. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]]
L_VERT_UP_RIGHT
[[1. 1. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 0.]]
L_VERT_DOWN_LEFT
[[0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [1. 1. 0. 0.]
 [0. 0. 0. 0.]]
L_VERT_DOWN_RIGHT
[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 1. 0. 0.]
 [0. 0. 0. 0.]]
Z_LEFT
[[1. 1. 0. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Z_RIGHT
[[0. 1. 1. 0.]
 [1. 1. 0. 0.]
 [0. 0.

In [35]:
def cell_index(coords):
    i = coords[0]
    j = coords[1]
    return i * 9 + j

In [36]:
cell_index((2, 3))

21

In [37]:
cell_index((8, 8))

80

In [38]:
def P_NEUTRAL_ENTRY(i, j, n):
    return list(map(cell_index, P_NEUTRAL(i, j))) + [P_OFFSET + n]

In [39]:
P_NEUTRAL_ENTRY(2, 3, 0)

[21, 81]

In [40]:
functions = [P_NEUTRAL, S_NEUTRAL, B_UP_DOWN, B_LEFT_RIGHT, L_UP_LEFT, L_UP_RIGHT, L_DOWN_LEFT, L_DOWN_RIGHT, L_VERT_UP_LEFT, L_VERT_UP_RIGHT, L_VERT_DOWN_LEFT, L_VERT_DOWN_RIGHT, Z_LEFT, Z_RIGHT, Z_UP, Z_DOWN, T_UP, T_DOWN, T_LEFT, T_RIGHT]

In [41]:
offsets = [P_OFFSET, S_OFFSET] + [B_OFFSET] * 2 + [L_OFFSET] * 8 + [Z_OFFSET] * 4 + [T_OFFSET] * 4

In [42]:
functions

[<function __main__.P_NEUTRAL(i, j)>,
 <function __main__.S_NEUTRAL(i, j)>,
 <function __main__.B_UP_DOWN(i, j)>,
 <function __main__.B_LEFT_RIGHT(i, j)>,
 <function __main__.L_UP_LEFT(i, j)>,
 <function __main__.L_UP_RIGHT(i, j)>,
 <function __main__.L_DOWN_LEFT(i, j)>,
 <function __main__.L_DOWN_RIGHT(i, j)>,
 <function __main__.L_VERT_UP_LEFT(i, j)>,
 <function __main__.L_VERT_UP_RIGHT(i, j)>,
 <function __main__.L_VERT_DOWN_LEFT(i, j)>,
 <function __main__.L_VERT_DOWN_RIGHT(i, j)>,
 <function __main__.Z_LEFT(i, j)>,
 <function __main__.Z_RIGHT(i, j)>,
 <function __main__.Z_UP(i, j)>,
 <function __main__.Z_DOWN(i, j)>,
 <function __main__.T_UP(i, j)>,
 <function __main__.T_DOWN(i, j)>,
 <function __main__.T_LEFT(i, j)>,
 <function __main__.T_RIGHT(i, j)>]

In [43]:
offsets

[81,
 82,
 87,
 87,
 89,
 89,
 89,
 89,
 89,
 89,
 89,
 89,
 93,
 93,
 93,
 93,
 97,
 97,
 97,
 97]

In [44]:
len(functions)

20

In [45]:
len(offsets)

20

In [46]:
functions_and_offsets_dict = {functions[i].__name__: (offsets[i]) for i in range(len(functions))}

In [47]:
functions_and_offsets_dict

{'P_NEUTRAL': 81,
 'S_NEUTRAL': 82,
 'B_UP_DOWN': 87,
 'B_LEFT_RIGHT': 87,
 'L_UP_LEFT': 89,
 'L_UP_RIGHT': 89,
 'L_DOWN_LEFT': 89,
 'L_DOWN_RIGHT': 89,
 'L_VERT_UP_LEFT': 89,
 'L_VERT_UP_RIGHT': 89,
 'L_VERT_DOWN_LEFT': 89,
 'L_VERT_DOWN_RIGHT': 89,
 'Z_LEFT': 93,
 'Z_RIGHT': 93,
 'Z_UP': 93,
 'Z_DOWN': 93,
 'T_UP': 97,
 'T_DOWN': 97,
 'T_LEFT': 97,
 'T_RIGHT': 97}

In [48]:
def ROW_ENTRY(func, i, j, n):
    return sorted(list(map(cell_index, func(i, j))) + [functions_and_offsets_dict[func.__name__] + n])

In [49]:
ROW_ENTRY(T_UP, 7, 6, 2)

[70, 78, 79, 80, 99]

In [50]:
P_ROWS = []
for i in range(9):
    for j in range(9):
        for n in range(P_NUMBER):
           P_ROWS.append(ROW_ENTRY(P_NEUTRAL, i, j, n))

In [51]:
S_ROWS = []
for i in range(8):
    for j in range(8):
        for n in range(S_NUMBER):
            S_ROWS.append(ROW_ENTRY(S_NEUTRAL, i, j, n))

In [52]:
B_ROWS = []
for i in range(9):
    for j in range(6):
        for n in range(B_NUMBER):
            B_ROWS.append(ROW_ENTRY(B_LEFT_RIGHT, i, j, n))
        
for i in range(6):
    for j in range(9):
        for n in range(B_NUMBER):
            B_ROWS.append(ROW_ENTRY(B_UP_DOWN, i, j, n))

In [53]:
T_ROWS = []
for i in range(8):
    for j in range(7):
            for n in range(T_NUMBER):
                T_ROWS.append(ROW_ENTRY(T_UP, i, j, n))
        
for i in range(8):
    for j in range(7):
            for n in range(T_NUMBER):
                T_ROWS.append(ROW_ENTRY(T_DOWN, i, j, n))
        
for i in range(7):
    for j in range(8):
            for n in range(T_NUMBER):
                T_ROWS.append(ROW_ENTRY(T_LEFT, i, j, n))
        
for i in range(7):
    for j in range(8):
            for n in range(T_NUMBER):
                T_ROWS.append(ROW_ENTRY(T_RIGHT, i, j, n))

In [54]:
L_ROWS = []
for i in range(8):
    for j in range(7):
            for n in range(L_NUMBER):
                L_ROWS.append(ROW_ENTRY(L_UP_LEFT, i, j, n))
        
for i in range(8):
    for j in range(7):
            for n in range(L_NUMBER):
                L_ROWS.append(ROW_ENTRY(L_UP_RIGHT, i, j, n))
                
for i in range(8):
    for j in range(7):
            for n in range(L_NUMBER):
                L_ROWS.append(ROW_ENTRY(L_DOWN_LEFT, i, j, n))
        
for i in range(8):
    for j in range(7):
            for n in range(L_NUMBER):
                L_ROWS.append(ROW_ENTRY(L_DOWN_RIGHT, i, j, n))
        
for i in range(7):
    for j in range(8):
            for n in range(L_NUMBER):
                L_ROWS.append(ROW_ENTRY(L_VERT_UP_LEFT, i, j, n))
        
for i in range(7):
    for j in range(8):
            for n in range(L_NUMBER):
                L_ROWS.append(ROW_ENTRY(L_VERT_UP_RIGHT, i, j, n))
                
for i in range(7):
    for j in range(8):
            for n in range(L_NUMBER):
                L_ROWS.append(ROW_ENTRY(L_VERT_DOWN_LEFT, i, j, n))
        
for i in range(7):
    for j in range(8):
            for n in range(L_NUMBER):
                L_ROWS.append(ROW_ENTRY(L_VERT_DOWN_RIGHT, i, j, n))

In [55]:
Z_ROWS = []
for i in range(8):
    for j in range(7):
            for n in range(Z_NUMBER):
                Z_ROWS.append(ROW_ENTRY(Z_LEFT, i, j, n))
        
for i in range(8):
    for j in range(7):
            for n in range(Z_NUMBER):
                Z_ROWS.append(ROW_ENTRY(Z_RIGHT, i, j, n))
        
for i in range(7):
    for j in range(8):
            for n in range(Z_NUMBER):
                Z_ROWS.append(ROW_ENTRY(Z_UP, i, j, n))
        
for i in range(7):
    for j in range(8):
            for n in range(Z_NUMBER):
                Z_ROWS.append(ROW_ENTRY(Z_DOWN, i, j, n))

In [56]:
ALL_ROWS = P_ROWS + S_ROWS + B_ROWS + L_ROWS + Z_ROWS + T_ROWS

In [57]:
len(ALL_ROWS)

4425

In [58]:
dlx_matrix = np.zeros((len(ALL_ROWS), 81+21), dtype=np.int32)

In [59]:
dlx_matrix

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int32)

In [60]:
for i in range(len(ALL_ROWS)):
    for item in ALL_ROWS[i]:
        dlx_matrix[i][item] = 1

In [61]:
dlx_matrix[256]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [62]:
dlx_matrix[50]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [63]:
def matrix_from_row_entry(row_entry):
    print(row_entry[:81].reshape((9, 9)))
    print(np.where(row_entry[81:] == 1)[0][0])

In [64]:
matrix_from_row_entry(dlx_matrix[529])

[[0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]
6


In [65]:
from IPython.display import clear_output
import time

In [67]:
for i in range(len(dlx_matrix)):
    clear_output(wait=True)
    time.sleep(0.05)
    matrix_from_row_entry(dlx_matrix[i])

[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1 1]
 [0 0 0 0 0 0 0 1 0]]
20


In [72]:
import sys
np.set_printoptions(threshold=np.inf)

In [75]:
print(dlx_matrix)

[[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 

In [69]:
import exact_cover as ec

In [ ]:
cover = ec.get_exact_cover(dlx_matrix)

In [ ]:
cover